myBloggieMVC/Models/Domain/BlogPost.cs
namespace myBloggieMVC.Models.Domain
{
	public class BlogPost
	{
        public Guid Id { get; set; }
        public string Heading { get; set; }
		public string PageTitle { get; set; }
		public string Content { get; set; }

		public string ShortDescription { get; set; }

		public string FeaturedImageUrl { get; set; }

		public string UrlHandle { get; set; }

		public DateTime PublishedDate { get; set; }

		public string Author { get; set; }

		public bool Visible { get; set; }

        public ICollection<Tag> Tag { get; set; }

    }
}

myBloggieMVC/Models/Domain/Tag.cs
namespace myBloggieMVC.Models.Domain
{
	public class Tag
	{
		public Guid Id { get; set; }

		public string Name { get; set; }
		public string DisplayName { get; set; }

        public ICollection<BlogPost> BlogPosts { get; set; }

    }
}

myBloggieMVC/Models/ErrorViewModel.cs
namespace myBloggieMVC.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

myBloggieMVC/Models/ViewModels/AddBlogPostRequest.cs
namespace myBloggieMVC.Models.ViewModels
{
    public class AddBlogPostRequest
    {
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string Content { get; set; }

        public string ShortDescription { get; set; }

        public string FeaturedImageUrl { get; set; }

        public string UrlHandle { get; set; }

        public DateTime PublishedDate { get; set; }

        public string Author { get; set; }

        public bool Visible { get; set; }
    }
}

myBloggieMVC/Models/ViewModels/AddTagRequest.cs
namespace myBloggieMVC.Models.ViewModels
{
    public class AddTagRequest
    {
        public string Name { get; set; }

        public string DisplayName { get; set; }
    }
}

myBloggieMVC/Models/ViewModels/EditTagRequest.cs
namespace myBloggieMVC.Models.ViewModels
{
    public class EditTagRequest
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
        public string DisplayName { get; set; }
    }
}

myBloggieMVC/Controllers/AdminBlogPostsController.cs
using Microsoft.AspNetCore.Mvc;

namespace myBloggieMVC.Controllers
{
    public class AdminBlogPostsController : Controller
    {
        [HttpGet]
        public IActionResult Add() 
        {
            return View();
        }
    }
}

myBloggieMVC/Controllers/AdminTagsController.cs
using myBloggieMVC.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Bloggie.Web.Data;
using myBloggieMVC.Models.Domain;
using Microsoft.EntityFrameworkCore;
using myBloggieMVC.Repositories;

namespace myBloggieMVC.Controllers
{
    public class AdminTagsController : Controller
    {
        private readonly ITagRespository tagRepository;

		public AdminTagsController(ITagRespository tagRepository)
        {
            this.tagRepository = tagRepository;
		}

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            // Mapping the AddTagRequest to Tag domain model
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };
            // moved lines to Add and Dave to Iterface
            await tagRepository.AddAsync(tag);

            return RedirectToAction("List"); 
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List() {

            var tags = await tagRepository.GetAllAsync(); 

			return View(tags);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id) 
        {
            var tag = await tagRepository.GetAsync(id);
            
            if (tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };

                return View(editTagRequest);
            }

           return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest) 
        {
            var tag = new Tag 
            { 
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName 
            };

           var updatedTag = await tagRepository.UpdateAsync(tag);

            if (updatedTag != null)
            {
                //Show success notification

            }
            else 
            {
                // Show Error notification
            }

            //Show Error notification
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }

        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
            var deletedTag = await tagRepository.DeleteAsync(editTagRequest.Id);

            if (deletedTag != null) 
            {
                //show success notification
                return RedirectToAction("List");       
            
            }

            // Show error notificaion
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }
    }
}

myBloggieMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using myBloggieMVC.Models;
using System.Diagnostics;

namespace myBloggieMVC.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

myBloggieMVC/Views/AdminBlogPosts/Add.cshtml
@model myBloggieMVC.Models.ViewModels.AddBlogPostRequest

@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Add new blogpost - Admin functionality
        </h1>
    </div>
</div>

<div class="container py-5">

    <form method="post">

        <div class="mb-3">
            <label class="form-label"> Heading </label>
            <input type="text" class="form-control" id="heading" asp-for="Heading" />
        </div>

        <div class="mb-3">
            <label class="form-label"> Page title </label>
            <input type="text" class="form-control" id="pageTitle" asp-for="PageTitle" />
        </div>

        <div class="mb-3">
            <label class="form-label">Content</label>
            <textarea class="form-control" id="content" asp-for="Content"></textarea>
        </div>

        <div class="mb-3">
            <label class="form-label"> Short description </label>
            <input type="text" class="form-control" id="shortDescription" asp-for="ShortDescription" />
        </div>

        <div class="mb-3">
            <label class="form-label"> Featured image URL </label>
            <input type="text" class="form-control" id="featuredImageUrl" asp-for="FeaturedImageUrl" />
        </div>

        <div class="mb-3">
            <label class="form-label"> URL handle </label>
            <input type="text" class="form-control" id="urlHandle" asp-for="UrlHandle" />
        </div>

        <div class="mb-3">
            <label class="form-label"> Published date </label>
            <input type="date" class="form-control" id="publishedDate" asp-for="PublishedDate" />
        </div>

        <div class="mb-3">
            <label class="form-label">Author</label>
            <input type="text" class="form-control" id="author" asp-for="Author" />
        </div>

        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" id="visible" asp-for="Visible">
            <label class="form-check-label">
                Is Visible?
            </label>
        </div>


        <div class="mb-3">
            <button type="submit" class="btn btn-dark">
                Save
        </button>



    </form>

</div>

myBloggieMVC/Views/AdminTags/Add.cshtml
@model myBloggieMVC.Models.ViewModels.AddTagRequest
        
@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Add new tag - Admin functionality
        </h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label"> Name </label>
            <input type="text" class="form-control" id="name" asp-for="Name" />
        </div>

        <div class="mb-3">
            <label class="form-label">Display name </label>
            <input type="text" class="form-control" id="displayName" asp-for="DisplayName" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

myBloggieMVC/Views/AdminTags/Edit.cshtml
@model myBloggieMVC.Models.ViewModels.EditTagRequest

@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Edit tag - Admin functionality
        </h1>
    </div>
</div>

<div class="container py-5" >

    @if (Model != null)
    {
        


    <form method="post">

        <div class="mb-3">
            <label class="form-label"> ID </label>
            <input class="form-control" type="text" id="id" asp-for="Id" readonly> </input>
        </div>

        <div class="mb-3">
            <label class="form-label"> Name </label>
            <input class="form-control" type="text" id="name" asp-for="Name"> </input>
        </div>

        <div class="mb-3">
            <label class="form-label"> Display name </label>
            <input class="form-control" type="text" id="displayName" asp-for="DisplayName"> </input>
        </div>

        <div class="mb-3">
            <div class="d-flex">
                <button type="submit" class="btn btn-dark"> Update </button>
                <button type="submit" class="btn btn-danger ms-2" asp-area="" asp-controller="AdminTags" asp-action="Delete"> Delete </button>
            </div>

        </div>

        </form>
    }
    else
    {
        <p>
            <h2>Tag not found</h2>
        </p>
    }

</div>

myBloggieMVC/Views/AdminTags/List.cshtml
@model List<myBloggieMVC.Models.Domain.Tag>

@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Show all tags - Admin functionality
        </h1>
    </div>
</div>

<div class="container py-5">

    @if (Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Display name</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var tag in Model)
                {
                    <tr>
                        <td>@tag.Id</td>
                        <td>@tag.Name</td>
                        <td>@tag.DisplayName</td>
                        <td>
                            <a asp-area="" asp-controller="AdminTags" asp-action="Edit" asp-route-id="@tag.Id"> Edit </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No Tags found! </p>
    }

</div>

myBloggieMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to my web</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

myBloggieMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myBloggieMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myBloggieMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myBloggieMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Add">Add tag </a> </li>
                                <a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="List">Display tags </a> </li>

                                <a class="dropdown-item" asp-area="" asp-controller="AdminBlogPosts" asp-action="Add">Add Blogpost </a> </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - myBloggieMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>